// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using myShopBoard.Data;

#nullable disable

namespace myShopBoard.Data.Migrations
{
    [DbContext(typeof(ShopBoardDbContext))]
    partial class ShopBoardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("myShopBoard.Data.Entities.Asset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("AssetStatusId")
                        .HasColumnType("bigint");

                    b.Property<long>("AssetTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("CurrentMeterAsOfUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentPrimaryMeter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("CurrentSecondaryMeter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("DateAquriedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateSoldUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DotExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("InServiceDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("InsuranceExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Make")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("OutOfServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("PrimaryMeterUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("QrTokenRotatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RegistrationExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryMeterUnit")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<long>("YardId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetStatusId");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("QrToken")
                        .IsUnique()
                        .HasDatabaseName("IX_Assets_QrToken_Unique");

                    b.HasIndex("UnitNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Assets_UnitNumber_Unique");

                    b.HasIndex("Vin")
                        .IsUnique()
                        .HasDatabaseName("IX_Assets_Vin_Unique")
                        .HasFilter("\"Vin\" IS NOT NULL");

                    b.HasIndex("YardId", "AssetStatusId")
                        .HasDatabaseName("IX_Assets_Yard_Status");

                    b.ToTable("Assets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssetStatusId = 1L,
                            AssetTypeId = 1L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentMeterAsOfUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrimaryMeter = 187432m,
                            CurrentSecondaryMeter = 9812m,
                            InServiceDate = new DateOnly(2019, 4, 12),
                            LicensePlate = "DT201",
                            Make = "Mack",
                            Model = "Granite GU713",
                            PrimaryMeterUnit = "mi",
                            QrToken = "u7Kq2mXfB9dLpR4wYc1Nzt",
                            SecondaryMeterUnit = "hr",
                            UnitNumber = "201",
                            Vin = "1FUJGLDR9CLBP1234",
                            YardId = 1L,
                            Year = 2019
                        },
                        new
                        {
                            Id = 2L,
                            AssetStatusId = 3L,
                            AssetTypeId = 1L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentMeterAsOfUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrimaryMeter = 224115m,
                            CurrentSecondaryMeter = 11240m,
                            InServiceDate = new DateOnly(2018, 8, 1),
                            LicensePlate = "DT202",
                            Make = "Peterbilt",
                            Model = "348",
                            PrimaryMeterUnit = "mi",
                            QrToken = "hV3sJ8nQwE5tZ1xA6yUm0P",
                            SecondaryMeterUnit = "hr",
                            UnitNumber = "202",
                            Vin = "1FUJGLDR1CLBP2345",
                            YardId = 1L,
                            Year = 2018
                        },
                        new
                        {
                            Id = 3L,
                            AssetStatusId = 1L,
                            AssetTypeId = 1L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentMeterAsOfUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrimaryMeter = 98774m,
                            CurrentSecondaryMeter = 5106m,
                            InServiceDate = new DateOnly(2021, 2, 18),
                            LicensePlate = "DT203",
                            Make = "Kenworth",
                            Model = "T880",
                            PrimaryMeterUnit = "mi",
                            QrToken = "Rf9bC2kL6vNhT4gW8jXs3Q",
                            SecondaryMeterUnit = "hr",
                            UnitNumber = "203",
                            Vin = "1FUJGLDR3CLBP3456",
                            YardId = 1L,
                            Year = 2021
                        },
                        new
                        {
                            Id = 4L,
                            AssetStatusId = 4L,
                            AssetTypeId = 1L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentMeterAsOfUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrimaryMeter = 291003m,
                            CurrentSecondaryMeter = 14775m,
                            InServiceDate = new DateOnly(2017, 6, 30),
                            LicensePlate = "DT204",
                            Make = "Mack",
                            Model = "Granite GU813",
                            PrimaryMeterUnit = "mi",
                            QrToken = "Yz5nD7pM1aS9fK3hJ6qV2L",
                            SecondaryMeterUnit = "hr",
                            UnitNumber = "204",
                            Vin = "1FUJGLDR5CLBP4567",
                            YardId = 2L,
                            Year = 2017
                        },
                        new
                        {
                            Id = 5L,
                            AssetStatusId = 8L,
                            AssetTypeId = 1L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentMeterAsOfUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrimaryMeter = 318990m,
                            CurrentSecondaryMeter = 16402m,
                            InServiceDate = new DateOnly(2016, 3, 22),
                            LicensePlate = "DT205",
                            Make = "Western Star",
                            Model = "4700SF",
                            PrimaryMeterUnit = "mi",
                            QrToken = "Qw8tG4rB6uH2mZ7cX1vN5J",
                            SecondaryMeterUnit = "hr",
                            UnitNumber = "205",
                            Vin = "1FUJGLDR7CLBP5678",
                            YardId = 2L,
                            Year = 2016
                        },
                        new
                        {
                            Id = 6L,
                            AssetStatusId = 1L,
                            AssetTypeId = 2L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentMeterAsOfUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrimaryMeter = 412556m,
                            CurrentSecondaryMeter = 12930m,
                            InServiceDate = new DateOnly(2020, 1, 15),
                            LicensePlate = "TR031",
                            Make = "Freightliner",
                            Model = "Cascadia 126",
                            PrimaryMeterUnit = "mi",
                            QrToken = "Ke2LxW9fP5sD8nA3jR7bU1",
                            SecondaryMeterUnit = "hr",
                            UnitNumber = "T-31",
                            Vin = "3AKJGLD52ESFR6789",
                            YardId = 1L,
                            Year = 2020
                        },
                        new
                        {
                            Id = 7L,
                            AssetStatusId = 2L,
                            AssetTypeId = 2L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentMeterAsOfUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrimaryMeter = 203881m,
                            CurrentSecondaryMeter = 6744m,
                            InServiceDate = new DateOnly(2022, 5, 9),
                            LicensePlate = "TR032",
                            Make = "Volvo",
                            Model = "VNL 760",
                            PrimaryMeterUnit = "mi",
                            QrToken = "Mv6yH1cJ4zQ7gT2pL9wF3S",
                            SecondaryMeterUnit = "hr",
                            UnitNumber = "T-32",
                            Vin = "3AKJGLD54ESFR7890",
                            YardId = 1L,
                            Year = 2022
                        },
                        new
                        {
                            Id = 8L,
                            AssetStatusId = 6L,
                            AssetTypeId = 2L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentMeterAsOfUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrimaryMeter = 355209m,
                            CurrentSecondaryMeter = 11018m,
                            InServiceDate = new DateOnly(2019, 9, 27),
                            LicensePlate = "TR033",
                            Make = "International",
                            Model = "LT625",
                            PrimaryMeterUnit = "mi",
                            QrToken = "Bn4qZ8dK2xV6mC1sY5tG7H",
                            SecondaryMeterUnit = "hr",
                            UnitNumber = "T-33",
                            Vin = "3AKJGLD56ESFR8901",
                            YardId = 2L,
                            Year = 2019
                        },
                        new
                        {
                            Id = 9L,
                            AssetStatusId = 1L,
                            AssetTypeId = 3L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InServiceDate = new DateOnly(2015, 7, 3),
                            LicensePlate = "TL051",
                            Make = "East",
                            Model = "Genesis End Dump",
                            PrimaryMeterUnit = "mi",
                            QrToken = "Cs1jN7vR3hL9bF4kW6zP2M",
                            UnitNumber = "TR-51",
                            YardId = 1L,
                            Year = 2015
                        },
                        new
                        {
                            Id = 10L,
                            AssetStatusId = 7L,
                            AssetTypeId = 3L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InServiceDate = new DateOnly(2018, 11, 14),
                            LicensePlate = "TL052",
                            Make = "Ranco",
                            Model = "LW22-40",
                            PrimaryMeterUnit = "mi",
                            QrToken = "Dp3fY6mT8wJ1qX5nH2cB9K",
                            UnitNumber = "TR-52",
                            YardId = 1L,
                            Year = 2018
                        },
                        new
                        {
                            Id = 11L,
                            AssetStatusId = 1L,
                            AssetTypeId = 4L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentMeterAsOfUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrimaryMeter = 61204m,
                            InServiceDate = new DateOnly(2022, 3, 1),
                            LicensePlate = "PU011",
                            Make = "Ford",
                            Model = "F-350",
                            PrimaryMeterUnit = "mi",
                            QrToken = "Gj7wS2bV5nM8xR3tK9dL4Q",
                            UnitNumber = "P-11",
                            Vin = "1FT8W3BT9NEC01234",
                            YardId = 1L,
                            Year = 2022
                        },
                        new
                        {
                            Id = 12L,
                            AssetStatusId = 1L,
                            AssetTypeId = 5L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentMeterAsOfUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrimaryMeter = 7318m,
                            InServiceDate = new DateOnly(2020, 10, 5),
                            Make = "Caterpillar",
                            Model = "950M",
                            PrimaryMeterUnit = "hr",
                            QrToken = "Ht5kP9zX1cN6vB2mQ8jW3F",
                            UnitNumber = "L-01",
                            YardId = 2L,
                            Year = 2020
                        });
                });

            modelBuilder.Entity("myShopBoard.Data.Entities.AssetStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("ExcludeFromAvailability")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInShop")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlannedDowntime")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetStatuses_Name_Unique");

                    b.ToTable("AssetStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ColorHex = "#16A34A",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExcludeFromAvailability = false,
                            IsAvailable = true,
                            IsInShop = false,
                            IsPlannedDowntime = false,
                            Name = "In Service",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 2L,
                            ColorHex = "#2563EB",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExcludeFromAvailability = false,
                            IsAvailable = false,
                            IsInShop = true,
                            IsPlannedDowntime = true,
                            Name = "Down - PM",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 3L,
                            ColorHex = "#DC2626",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExcludeFromAvailability = false,
                            IsAvailable = false,
                            IsInShop = true,
                            IsPlannedDowntime = false,
                            Name = "Down - Shop Repair",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = 4L,
                            ColorHex = "#EA580C",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExcludeFromAvailability = false,
                            IsAvailable = false,
                            IsInShop = true,
                            IsPlannedDowntime = false,
                            Name = "Down - Waiting Parts",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = 5L,
                            ColorHex = "#CA8A04",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExcludeFromAvailability = false,
                            IsAvailable = false,
                            IsInShop = true,
                            IsPlannedDowntime = false,
                            Name = "Down - Waiting Authorization",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = 6L,
                            ColorHex = "#B91C1C",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExcludeFromAvailability = false,
                            IsAvailable = false,
                            IsInShop = false,
                            IsPlannedDowntime = false,
                            Name = "Down - Road Call",
                            SortOrder = 60
                        },
                        new
                        {
                            Id = 7L,
                            ColorHex = "#7C3AED",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExcludeFromAvailability = false,
                            IsAvailable = false,
                            IsInShop = true,
                            IsPlannedDowntime = true,
                            Name = "Down - DOT Inspection",
                            SortOrder = 70
                        },
                        new
                        {
                            Id = 8L,
                            ColorHex = "#64748B",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExcludeFromAvailability = true,
                            IsAvailable = false,
                            IsInShop = false,
                            IsPlannedDowntime = false,
                            Name = "Seasonal / Parked",
                            SortOrder = 80
                        },
                        new
                        {
                            Id = 9L,
                            ColorHex = "#334155",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExcludeFromAvailability = true,
                            IsAvailable = false,
                            IsInShop = false,
                            IsPlannedDowntime = false,
                            Name = "Out of Fleet",
                            SortOrder = 90
                        });
                });

            modelBuilder.Entity("myShopBoard.Data.Entities.AssetType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("DefaultPrimaryMeterUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DefaultSecondaryMeterUnit")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("RequiresDotAnnual")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetTypes_Name_Unique");

                    b.ToTable("AssetTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultPrimaryMeterUnit = "mi",
                            DefaultSecondaryMeterUnit = "hr",
                            Name = "Dump Truck",
                            RequiresDotAnnual = true
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultPrimaryMeterUnit = "mi",
                            DefaultSecondaryMeterUnit = "hr",
                            Name = "Tractor",
                            RequiresDotAnnual = true
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultPrimaryMeterUnit = "mi",
                            Name = "Trailer",
                            RequiresDotAnnual = true
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultPrimaryMeterUnit = "mi",
                            Name = "Pickup",
                            RequiresDotAnnual = false
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultPrimaryMeterUnit = "hr",
                            Name = "Loader",
                            RequiresDotAnnual = false
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultPrimaryMeterUnit = "mi",
                            Name = "Box Truck",
                            RequiresDotAnnual = false
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultPrimaryMeterUnit = "mi",
                            DefaultSecondaryMeterUnit = "hr",
                            Name = "Service Truck",
                            RequiresDotAnnual = true
                        });
                });

            modelBuilder.Entity("myShopBoard.Data.Entities.Yard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.Property<string>("address2")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Yards_Code_Unique");

                    b.ToTable("Yards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "MAIN",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Main Yard"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "NORTH",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "North Terminal"
                        });
                });

            modelBuilder.Entity("myShopBoard.Data.Entities.Asset", b =>
                {
                    b.HasOne("myShopBoard.Data.Entities.AssetStatus", "AssetStatus")
                        .WithMany("Assets")
                        .HasForeignKey("AssetStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("myShopBoard.Data.Entities.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("myShopBoard.Data.Entities.Yard", "Yard")
                        .WithMany("Assets")
                        .HasForeignKey("YardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetStatus");

                    b.Navigation("AssetType");

                    b.Navigation("Yard");
                });

            modelBuilder.Entity("myShopBoard.Data.Entities.AssetStatus", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("myShopBoard.Data.Entities.AssetType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("myShopBoard.Data.Entities.Yard", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
